version: '3'
services:
  app:
    build: .
    image: docker-registry.internal/ninech/docker-example
    volumes:
      - ./app:/app/app
      - ./bin:/app/bin
      - ./config:/app/config
      - ./db:/app/db
      - ./lib:/app/lib
      - ./public:/app/public
      - ./test:/app/test
    ports:
      - 3000
    depends_on:
      - postgres
      - zipkin
    environment:
      - POSTGRES_PASSWORD=frankenstein
  postgres:
    image: postgres:9.5-alpine
    environment:
      - POSTGRES_PASSWORD
  zipkin:
    image: openzipkin/zipkin:1.26
    ports:
      - 9411
