version: '3'
services:
  app:
    build: .
    image: docker-registry.internal/ninech/docker-example
    volumes:
      - .:/app
    ports:
      - 3000
    depends_on:
      - postgres
    environment:
      - POSTGRES_PASSWORD=frankenstein
  postgres:
    image: postgres:9.5-alpine
    environment:
      - POSTGRES_PASSWORD
